import * as monaco from 'monaco-editor';

// Custom theme for Monaco Editor
export const setupCustomTheme = (monacoInstance: typeof monaco) => {
  // Define a custom theme
  monacoInstance.editor.defineTheme('pynote-theme', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: '', foreground: 'e2e8f0', background: '0f172a' },
      { token: 'comment', foreground: '64748b', fontStyle: 'italic' },
      { token: 'keyword', foreground: '818cf8', fontStyle: 'bold' },
      { token: 'type', foreground: '60a5fa' },
      { token: 'string', foreground: '34d399' },
      { token: 'number', foreground: 'f472b6' },
      { token: 'delimiter.bracket', foreground: '94a3b8' },
      { token: 'delimiter', foreground: '94a3b8' },
      { token: 'identifier', foreground: 'e2e8f0' },
      { token: 'operator', foreground: 'f472b6' },
      { token: 'variable', foreground: 'e2e8f0' },
      { token: 'variable.predefined', foreground: '818cf8' },
      { token: 'function', foreground: '60a5fa' },
      { token: 'class', foreground: '60a5fa' },
      { token: 'tag', foreground: 'f472b6' },
      { token: 'attribute.name', foreground: 'fbbf24' },
      { token: 'attribute.value', foreground: '34d399' },
    ],
    colors: {
      'editor.background': '#0f172a',
      'editor.foreground': '#e2e8f0',
      'editor.lineHighlightBackground': '#1e293b80',
      'editorLineNumber.foreground': '#64748b',
      'editorLineNumber.activeForeground': '#e2e8f0',
      'editor.selectionBackground': '#3b82f640',
      'editor.inactiveSelectionBackground': '#3b82f620',
      'editorCursor.foreground': '#e2e8f0',
      'editorWhitespace.foreground': '#334155',
      'editorIndentGuide.background': '#1e293b',
      'editorIndentGuide.activeBackground': '#334155',
      'editor.selectionHighlightBorder': '#3b82f600',
      'editorBracketMatch.background': '#3b82f620',
      'editorBracketMatch.border': '#3b82f680',
      'editorGutter.background': '#0f172a',
      'editorSuggestWidget.background': '#0f172a',
      'editorSuggestWidget.border': '#1e293b',
      'editorSuggestWidget.selectedBackground': '#1e40af',
      'editorHoverWidget.background': '#0f172a',
      'editorHoverWidget.border': '#1e293b',
    },
  });
};

// Custom editor options
export const editorOptions: monaco.editor.IStandaloneEditorConstructionOptions = {
  fontFamily: "'Fira Code', 'Courier New', monospace",
  fontSize: 14,
  lineHeight: 20,
  fontWeight: '400',
  fontLigatures: true,
  lineNumbers: 'off',
  minimap: { enabled: false },
  scrollBeyondLastLine: false,
  scrollbar: {
    vertical: 'hidden',
    horizontal: 'hidden',
    useShadows: false,
    verticalHasArrows: false,
    horizontalHasArrows: false,
    verticalScrollbarSize: 8,
    horizontalScrollbarSize: 8,
  },
  overviewRulerLanes: 0,
  hideCursorInOverviewRuler: true,
  folding: false,
  glyphMargin: false,
  lineDecorationsWidth: 0,
  lineNumbersMinChars: 0,
  automaticLayout: true,
  padding: { top: 8, bottom: 8 },
  renderLineHighlight: 'none',
  contextmenu: false,
  matchBrackets: 'always',
  autoClosingBrackets: 'always',
  autoClosingQuotes: 'always',
  autoIndent: 'full',
  formatOnPaste: true,
  formatOnType: true,
  suggestOnTriggerCharacters: true,
  wordBasedSuggestions: 'allDocuments',
  quickSuggestions: { 
    comments: 'on',
    other: 'on',
    strings: 'on' 
  },
  parameterHints: { enabled: true },
  suggest: {
    showKeywords: true,
    showSnippets: true,
    showClasses: true,
    showFunctions: true,
    showVariables: true,
    showModules: true,
    showFiles: true,
    showReferences: true,
    showValues: true,
    showConstants: true,
    showTypeParameters: true,
    showEnums: true,
    showStructs: true,
    showInterfaces: true,
    showConstructors: true,
    showProperties: true,
    showEvents: true,
    showOperators: true,
    showUnits: true,
    showUsers: true,
    showIssues: true,
    showFolders: true,
    showInlineHints: true,
  } as monaco.editor.ISuggestOptions,
};
